on:
  push:
    branches:
    - main

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: |
          git config --local user.email "plutotcool+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - run: |
         pnpm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
      - run: pnpm install
      - run: pnpm build
      - run: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
